# Generated by Django 5.2.7 on 2025-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
